name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Linter
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Install Deps
      run: |
        pip install -r backend/requirements.txt
        pip install -r frontend/requirements.txt
    - name: Lint Application Code
      run: |
        pylint --fail-under=9 $(git ls-files '*.py')
